import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // API Reference Sidebar
  apiSidebar: [
    {
      type: 'category',
      label: 'API Reference',
      collapsed: false,
      items: [
        'api-reference/welcome',
        'api-reference/index',
        'api-reference/quick-start',
        {
          type: 'category',
          label: 'Authentication',
          items: ['api-reference/authentication/index'],
        },
        {
          type: 'category',
          label: 'Sender ID',
          items: ['api-reference/sender-id/index'],
        },
        {
          type: 'category',
          label: 'Contacts',
          items: ['api-reference/contacts/index'],
        },
        {
          type: 'category',
          label: 'SMS',
          items: ['api-reference/sms/index'],
        },
        {
          type: 'category',
          label: 'Balance',
          items: ['api-reference/balance/index'],
        },
        {
          type: 'category',
          label: 'Voice',
          items: ['api-reference/voice/index'],
        },
      ],
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
